backend:
  name: git-gateway
  branch: main # GitHub'daki ana branch adınız (main veya master)

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "Yazılar"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Yayın Tarihi", name: "date", widget: "datetime" }
      - { label: "Öne Çıkan Görsel", name: "image", widget: "image", required: false }
      - { label: "İçerik", name: "body", widget: "markdown" }